// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRAOxuh-Y4AG3dcfzaG4Rzoserq52yP8',
    appId: '1:171544335863:web:572087400d7bbe0b240af2',
    messagingSenderId: '171544335863',
    projectId: 'socially-a4b3f',
    authDomain: 'socially-a4b3f.firebaseapp.com',
    storageBucket: 'socially-a4b3f.firebasestorage.app',
    measurementId: 'G-ZX3TLZ3KKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRw59mQ-AqABBxenR0_D1-X6-64CV2XUA',
    appId: '1:171544335863:android:c666fae4e7310a8b240af2',
    messagingSenderId: '171544335863',
    projectId: 'socially-a4b3f',
    storageBucket: 'socially-a4b3f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO7_wDyEUXZY7y8JVCNe7iUAgvIcg152U',
    appId: '1:171544335863:ios:b87f06da6922714c240af2',
    messagingSenderId: '171544335863',
    projectId: 'socially-a4b3f',
    storageBucket: 'socially-a4b3f.firebasestorage.app',
    iosBundleId: 'com.example.socially',
  );
}
